// Automatically generated by astro-icon
// e7afef1593f594ace9e3e30f2f19448c5ca037c85281ef5dc98441f789203433

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "heart-empty"
		| "heart-filled";
}